# Generated by Django 5.0.7 on 2024-07-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.CharField(max_length=100, verbose_name='slug')),
                ('body', models.CharField(max_length=100, verbose_name='Содержание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Изображение')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('count_review', models.IntegerField()),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
                'ordering': ['title', 'is_published', 'count_review'],
            },
        ),
    ]
